### ISSUE TITLE
when i run the file lcss_neignbors.py，there are no result in my context

### ISSUE THREAD

**Issue by yaowanwei96** [jim-spyropoulos/Trajectory-Analysis-and-Classification-in-Python-Pandas-and-Scikit-Learn-#1]
the file is 0kB ,but the DTW method is right.

**Comment by jim-spyropoulos** [comment]
In order to properly run lcss_neighbors.py, you need to produce the pickle file named **final_cleaned.df**.
Execution of datacleaning.py outputs this file.
