### ISSUE TITLE
zero point

### ISSUE THREAD

**Issue by tingtingwen1995** [jim-spyropoulos/Trajectory-Analysis-and-Classification-in-Python-Pandas-and-Scikit-Learn-#2]
How did you confirm the zero point in grid_points file，the grids.csv file don’t  have JourneyPatternId column，so i add a JourneyPatternId column。

**Comment by jim-spyropoulos** [comment]
@tingtingwen1995 
Zero point as well as cell size paremeters were chosen based on the given dataset and the desired accuracy.
As zero point, we considered it to be the downmost & leftmost point of the input trajectories. The zero point is computed in file [down_left_point.py](https://github.com/jim-spyropoulos/Trajectory-Analysis-and-Classification-in-Python-Pandas-and-Scikit-Learn-/blob/master/down_left_point.py)
