### ISSUE TITLE
Grids in classifytraj.py ?

### ISSUE THREAD

**Issue by dickwxyz** [jim-spyropoulos/Trajectory-Analysis-and-Classification-in-Python-Pandas-and-Scikit-Learn-#4]
When I ran the classifytraj.py, df has no column named 'Grids' (It is in the grids.csv)? Do you miss any codes here?

```
df=pd.read_csv("train_set.csv",error_bad_lines=False)    
df = df[pd.notnull(df['journeyPatternId'])] #deletes null values from dataset     
#print(df)    
le = preprocessing.LabelEncoder()    
le.fit(df["journeyPatternId"])    
Y_train=le.transform(df["journeyPatternId"])  
X_train1=df['Grids']      
print(X_train1)     
```

**Comment by jim-spyropoulos** [comment]
@dickwxyz It is in the grid.csv file, which is produced by [grid_points.py](https://github.com/jim-spyropoulos/Trajectory-Analysis-and-Classification-in-Python-Pandas-and-Scikit-Learn/blob/master/grid_points.py)
Also, journeyPatternId should be replaced by TripId.
